version: '3.7'
services:
  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.21.0
    restart: always
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${PSQL_HOST}
            port: ${PSQL_PORT}
            database: ${PSQL_DATABASE}
            ssl: ${PSQL_SSL} 
            user: ${PSQL_USER}
            password: ${PSQL_PASSWORD}
            migrations: true

  node:
    container_name: node
    restart: always
    build: ./
    command: ${COMMAND}
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
